### PR TITLE
Fix killing in the name of... tasks

### LINKED ISSUE #361: [Bug]: Killing in the name of BUG
### What happened?

When a player ask for example to start Trolls task player get automatically Necromancer & Priestess task and if a player kills 1 troll the Necromancer & Priestess task count goes up but the Troll count keeps on 0. 
Also if player ask for Goblins tasks u get Minotaurs task instead (pretty sure some other tasks are wrong?)

### How to Reproduce?

Just ask Grizzly Adams for a task, and ask for Trolls tasks then for goblins tasks and u'll get another tasks instead of what player asked for

### Relevant log output

_No response_

### Attach any relevant file

127 0 0 1_client_57pbjRSxKU
127 0 0 1_client_5jyw1C3FXG

### Version

12.x (Default)

### What OS are you seeing the problem on?

Windows 10

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### LINKED ISSUE #686: "Quest log updated" on "Killing in the name of..."
### Priority

Low

### Area

- [ ] Datapack
- [ ] Source
- [ ] Map
- [X] Other

### What happened?

This is super low priority but, when killing anything on a task will receive the following message

image

Is there a way to remove this so it only does it once you finish the quest?

### What OS are you seeing the problem on?

Ubuntu 20.04, Ubuntu 22.04

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### LINKED ISSUE #708: War Turmoil (Killing in the name of : Mino Task)
### Priority

Low

### Area

- [ ] Datapack
- [ ] Source
- [ ] Map
- [X] Other

### What happened?

After killing 5000 minos from budrik my player has the correct Storages 

image

image

Quest log does not update, budrik already says the text as if he had already killed The horned fox, the quest remains in the log, and he cannot go into the portal

image

My player asked for task again and he got the task to go killed the horned fox but he cannot go thru the portal still
image

### What OS are you seeing the problem on?

Ubuntu 20.04, Ubuntu 22.04

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### LINKED ISSUE #736: [MAP] Missing elements
### Priority

Low

### Area

- [ ] Datapack
- [ ] Source
- [X] Map
- [ ] Other

### What happened?

Fixes need for #731
- [x] {x = 32870, y = 31112, z = 4} teleport missing

<details>
  <summary>Click to expand!</summary>

image
image
</details>

- [x] {x = 32878, y = 31119, z = 8} teleport missing destination `{x = 32870, y = 31114, z = 4}`

- [x] {x = 32814, y = 31120, z = 2} teleport missing destination `{x = 32813, y = 31119, z = 3}`

- [x] {x = 32821, y = 31112, z = 7} {x = 32822, y = 31112, z = 7} {x = 32869, y = 31105, z = 7} {x = 32869, y = 31106, z = 7} doors should be quest type

<details>
  <summary>Click to expand!</summary>

image
image
image
image
</details>

- [x] {x = 32807, y = 31117, z = 2} fire missing

<details>
  <summary>Click to expand!</summary>

image
image
</details>

- [x] List of uid that can be removed from map:
from 3230 to 3262 on positions:

<details>
  <summary>Click to expand!</summary>

- {x = 32608, y = 32714, z = 8}
- {x = 32822, y = 32693, z = 8}
- {x = 32722, y = 32762, z = 8}
- {x = 32104, y = 31116, z = 2}
- {x = 32141, y = 31144, z = 3}
- {x = 32758, y = 31245, z = 9}
- {x = 33044, y = 32794, z = 11}
- {x = 33109, y = 32803, z = 13}
- {x = 32122, y = 31188, z = 4}
- {x = 32085, y = 32782, z = 12}
- {x = 32814, y = 32280, z = 8}
- {x = 32992, y = 31443, z = 7}
- {x = 32072, y = 31283, z = 10}
- {x = 32816, y = 31026, z = 7}
- {x = 33310, y = 31183, z = 7}
- {x = 33136, y = 31186, z = 8}
- {x = 33286, y = 31112, z = 8}
- {x = 32679, y = 31114, z = 3}
- {x = 32920, y = 32883, z = 8}
- {x = 32842, y = 32660, z = 11}
- {x = 32799, y = 32501, z = 11}
- {x = 33251, y = 31719, z = 14}
- {x = 31926, y = 31071, z = 10}
- {x = 32044, y = 32547, z = 14}
- {x = 33115, y = 31004, z = 8}
- {x = 33066, y = 31104, z = 2}
- {x = 32003, y = 31189, z = 10}
- {x = 33095, y = 31075, z = 12}
- {x = 32877, y = 32583, z = 7}
- {x = 32769, y = 32290, z = 10}
- {x = 33046, y = 32439, z = 11}
- {x = 32450, y = 31988, z = 9}
- {x = 31978, y = 32853, z = 1}
</details>

### What OS are you seeing the problem on?

Windows 10

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by rigis1**
# Description
Few problems will be resolved in #736
## Adds:

- boss points, now after finish tasks when you have boss activated but not finished you will be rewarded with boss point
- extra points, now when you have low amount of points when you have level 130+ you will be rewarded with extra
- free boss, first time kill boss from lower tier will not cost boss points
- points cap, when you reach point cap you will not receive points after complete task
- djinns task
- pirate task
- daniel steelsoul tasks
- djinn boss: merikh the slaughterer

## Fix:

- grizzly adams now will not give you tasks that belongs to others npc.
- ranks promotion, now after collect proper amount of points you will receive rank promotion
- achievements after boss kill, now you have to kill boss to receive achievement
- questlogs description
- demon task, now is not repeatable
- minotaur task
- necromancer task

## Changes:

- changed from quest log kill counter to storage kill counter, now kills will not send you quest log update spam
- messages from grizzly adams, now will be more like global
- questlog entries, now will be more like global
- boss script from uid to position
- tasks are now grouped by npc

## Fixes

#686 
#708

## Type of change

  - [x] Bug fix (non-breaking change which fixes an issue)

## Checklist

  - [x] My code follows the style guidelines of this project
  - [x] I have performed a self-review of my own code
  - [x] I checked the PR checks reports
  - [x] I have commented my code, particularly in hard-to-understand areas
  - [ ] I have made corresponding changes to the documentation
  - [x] My changes generate no new warnings
  - [ ] I have added tests that prove my fix is effective or that my feature works

### CODE REVIEW

**Review by majestyotbr — APPROVED** [review]

File: data/lib/core/storages.lua [hunk 1]
```diff
@@ -2111,7 +2117,176 @@ Storage = {
 			Braindeath = {},
 			DarashiaDragon = {},
 			HotCuisine = {},
-			KillingInTheNameOf = {},
+			KillingInTheNameOf = {
+				MonsterKillCount = {
+					KillCount = 42150,
```
Comment (bosmak) [inline data/lib/core/storages.lua:2122]: nitpicking: Shouldn't the id start as `42151` like the commented range on U8_5 or at least update the comment?

Comment (rigis1) [reply data/lib/core/storages.lua:2122]: changed comment

**Comment by majestyotbr** [comment]
Thanks for your contribution.
Updated otservbr-global map available in:
https://github.com/opentibiabr/otservbr-global/releases/download/stable-v1.4.0/otservbr.otbm
