### PR TITLE
Fix Warzones I, II & III

### LINKED ISSUE #718: Big foot burden  : MatchMaker Daily Task
### Priority

Medium

### Area

- [ ] Datapack
- [ ] Source
- [ ] Map
- [X] Other

### What happened?

The "Matchmaker" daily task does not work, all of the crystals return the following message "This is not the crystal you are looking for" however there are no more crystals to use

image

image

### What OS are you seeing the problem on?

Ubuntu 20.04, Ubuntu 22.04

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by murilo09**
# Description

Several fixes in Warzoes I, II & III

Necessary map changes:
- Remove UIDs and AIDs from position these positions:

> - [x] {x = 32751, y = 31789, z = 10}
> - [x] {x = 32753, y = 31789, z = 10}
> - [x] {x = 32755, y = 31789, z = 10}
> - [x] {x = 33013, y = 31880, z = 9}
> - [x] {x = 33019, y = 31886, z = 9}
> - [x] {x = 33022, y = 31902, z = 9}
> - [x] {x = 32767, y = 31771, z = 10}
> - [x] {x = 32628, y = 31863, z = 11}
> - [x] {x = 32330, y = 32173, z = 9}
> - [x] {x = 32403, y = 32818, z = 6}
> - [x] {x = 33187, y = 32384, z = 8}
> - [x] {x = 32196, y = 31183, z = 8}
> - [x] {x = 33154, y = 31834, z = 10}
> - [x] {x = 32803, y = 31798, z = 9}
> - [x] {x = 32795, y = 31761, z = 10}
> - [x] {x = 33000, y = 31871, z = 13}
> - [x] {x = 32803, y = 31745, z = 10}
> - [x] {x = 32864, y = 31845, z = 11}
> - [x] {x = 32796, y = 31780, z = 10}
> - [x] {x = 32986, y = 31861, z = 9}
> - [x] {x = 33001, y = 31916, z = 9}
> - [x] {x = 32959, y = 31952, z = 9}
> - [x] {x = 32980, y = 31907, z = 9}
> - [x] {x = 32904, y = 31893, z = 13}
> - [x] {x = 32805, y = 31743, z = 9}
> - [x] {x = 32786, y = 31754, z = 9}
> - [x] {x = 32772, y = 31776, z = 9}
> - [x] {x = 32831, y = 31797, z = 9}
> - [x] {x = 32827, y = 31757, z = 9}
> - [x] {x = 32789, y = 31796, z = 10}
> - [x] {x = 32772, y = 31799, z = 10}
> - [x] {x = 32764, y = 31758, z = 10}
> - [x] {x = 32765, y = 31758, z = 10}
> - [x] {x = 32766, y = 31758, z = 10}
> - [x] {x = 32764, y = 31759, z = 10}
> - [x] {x = 32765, y = 31759, z = 10}
> - [x] {x = 32766, y = 31759, z = 10}
> - [x] {x = 32764, y = 31760, z = 10}
> - [x] {x = 32765, y = 31760, z = 10}
> - [x] {x = 32766, y = 31760, z = 10}
> - [x] {x = 32764, y = 31761, z = 10}
> - [x] {x = 32765, y = 31761, z = 10}
> - [x] {x = 32766, y = 31761, z = 10}
> - [x] {x = 32764, y = 31762, z = 10}
> - [x] {x = 32765, y = 31762, z = 10}
> - [x] {x = 32766, y = 31762, z = 10}
> - [x] {x = 32764, y = 31763, z = 10}
> - [x] {x = 32765, y = 31763, z = 10}
> - [x] {x = 32766, y = 31763, z = 10}
> - [x] {x = 32767, y = 31763, z = 10}
> - [x] {x = 32776, y = 31804, z = 10}
> - [x] {x = 32781, y = 31807, z = 10}
> - [x] {x = 32777, y = 31812, z = 10}
> - [x] {x = 32771, y = 31810, z = 10}

- Remove Sign in position 32768, 31771, 10.

## Issues

#718 

## Type of change

Please delete options that are not relevant.

  - [X] Bug fix (non-breaking change which fixes an issue)
  - [X] New feature (non-breaking change which adds functionality)

## Checklist

  - [X] My code follows the style guidelines of this project
  - [X] I have performed a self-review of my own code
  - [X] I checked the PR checks reports
  - [X] My changes generate no new warnings

### CODE REVIEW

File: data/scripts/movements/quests/bigfoot_burden/task_ear.lua [hunk 1]
```diff
@@ -0,0 +1,72 @@
...
+		for i = player:getStorageValue(Storage.BigfootBurden.GnomedixMsg), #messages do
+			addEvent(sendTextMessages, (i - 1) * 4000, player.uid, i, player:getPosition())
+		end
+
+	end
+	return true
+end
+
+taskEar:type("stepin")
+taskEar:uid(3123)
```
Comment (rigis1) [inline data/scripts/movements/quests/bigfoot_burden/task_ear.lua:71]:
```suggestion
taskEar:position({x = 32767, y = 31771, z = 10})
```

Comment (murilo09) [inline data/scripts/movements/quests/bigfoot_burden/task_ear.lua]: I'll test it later and commit

File: data/scripts/movements/quests/bigfoot_burden/task_ear.lua [hunk 2]
```diff
@@ -0,0 +1,72 @@
...
+taskEar:register()
```
Comment (rigis1) [inline data/scripts/movements/quests/bigfoot_burden/task_ear.lua]:
```suggestion
local messages = {
	{"Gnomedix: So let the examination begin! Now don't move. Don't be afraid. The good doctor gnome won't hurt you - hopefully!", CONST_ME_LOSEENERGY},
	{"Gnomedix: Now! Now! Don't panic! It's all over soon!"},
	{"Gnomedix: Let me try a bigger chisel!", CONST_ME_POFF},
	{"Gnomedix: We're almost don... holy gnome! What's THIS???"},
	{"Gnomedix: I need a drill! Gnomenursey, quick!"},
	{"Gnomedix: Hold still now! This might tickle a little..", CONST_ME_STUN},
	{"Gnomedix: Take this, you evil ... whatever you are!"},
	{"Gnomedix: I got it! Yikes! What was that? Uhm, well ... you passed the ear examination. Talk to Gnomaticus for your next test.", CONST_ME_BLOCKHIT}
}

local function sendTextMessages(cid, index)
	local player = Player(cid)
	if not player then
		return true
	end

	if index ~= player:getStorageValue(Storage.BigfootBurden.GnomedixMsg) then
		return false
	end

	if player:getPosition() ~= Position({x = 32767, y = 31771, z = 10}) then
		return false
	end

	player:sendTextMessage(MESSAGE_EVENT_ADVANCE, messages[index][1])
	if messages[index][2] then
		player:getPosition():sendMagicEffect(messages[index][2])
	end
	player:setStorageValue(Storage.BigfootBurden.GnomedixMsg,
	player:getStorageValue(Storage.BigfootBurden.GnomedixMsg) + 1)
	if index == 8 then
		Game.createMonster("Strange Slime", Position(32767, 31772, 10))
		player:setStorageValue(Storage.BigfootBurden.QuestLine, 11)
	end
end

local condition = Condition(CONDITION_OUTFIT)
condition:setTicks(2000)
condition:setOutfit({lookType = 33}) -- skeleton looktype

local taskEar = MoveEvent()
function taskEar.onStepIn(creature, item, position, fromPosition)
	local player = creature:getPlayer()
	if not player then
		return true
	end

	if player:getStorageValue(Storage.BigfootBurden.QuestLine) ~= 10 then
		return true
	end
	player:setStorageValue(Storage.BigfootBurden.GnomedixMsg, 1)
	position:sendMagicEffect(CONST_ME_LOSEENERGY)

	for i = player:getStorageValue(Storage.BigfootBurden.GnomedixMsg), #messages do
		addEvent(sendTextMessages, (i - 1) * 4000, player.uid, i)
	end
	return true
end

taskEar:position({x = 32767, y = 31771, z = 10})
taskEar:register()

```
Rest of changes you can get on discord english channel, test it if you can. [discord channel](https://discord.com/channels/528117503952551936/838521137793204234)

Comment (murilo09) [reply data/scripts/movements/quests/bigfoot_burden/task_ear.lua]: I can't reply you in that channel, but i saw your messages. I didn't create any scripts, just reused the scripts that already were in the datapack, i'll test your changes later. Thanks!

Comment (rigis1) [reply data/scripts/movements/quests/bigfoot_burden/task_ear.lua]: > I can't reply you in that channel, but i saw your messages. I didn't create any scripts, just reused the scripts that already were in the datapack, i'll test your changes later. Thanks!

if you have any question just ask on general chat.

File: data/npc/gnomeral.lua [hunk 3]
```diff
@@ -77,7 +82,7 @@ local function creatureSayCallback(npc, creature, type, message)
 			}, npc, creature)
 				player:setStorageValue(Storage.BigfootBurden.MissionMatchmaker, 1)
 				player:setStorageValue(Storage.BigfootBurden.MatchmakerStatus, 0)
-				player:setStorageValue(Storage.BigfootBurden.MatchmakerIdNeeded, math.random(18320, 18326))
+				player:setStorageValue(Storage.BigfootBurden.MatchmakerIdNeeded, math.random(15809, 15815))
```
Comment (murilo09) [inline data/npc/gnomeral.lua:85]: Fixing issue #718

File: data/npc/gnomad.lua [hunk 4]
```diff
@@ -50,6 +50,48 @@ npcType.onCloseChannel = function(npc, creature)
...
+    elseif (MsgContains(message, "gnomes")) then
+        npcHandler:say(
+            "We gnomes are masters of growing and working crystals and we also mastered the raising of a variety of mushrooms for different purposes.",
+            npc, creature)
+        npcHandler:setTopic(playerId, 0)
+    end
+    return true
+end
+
+npcHandler:setMessage(MESSAGE_GREET, 'Hi there! I\'m ready to brief you with {tactical} advice.')
```
Comment (rigis1) [inline data/npc/gnomad.lua]:
```suggestion
npcHandler:setMessage(MESSAGE_GREET, "Hi there! I'm ready to brief you with {tactical} advice.")
```

File: data/npc/gnomelvis.lua [hunk 5]
```diff
@@ -99,8 +99,9 @@ local function creatureSayCallback(npc, creature, type, message)
 	return true
 end
 
+npcHandler:setMessage(MESSAGE_GREET, 'Hello. Is it me you\'re {looking} for?')
```
Comment (rigis1) [inline data/npc/gnomelvis.lua]:
```suggestion
npcHandler:setMessage(MESSAGE_GREET, "Hello. Is it me you're {looking} for?")
```

File: data/npc/gnomercy.lua [hunk 6]
```diff
@@ -49,6 +49,34 @@ npcType.onCloseChannel = function(npc, creature)
...
+			 "You'd better be finished with them before Versperoth re-emerges. ...",
+			 "Only when you manage to kill Versperoth, will you be able to enter the portal behind him and face the true evil of the observer. ...",
+             "Use the GREEN command crystal in the cave to begin the charging of the teleport! Good luck."}, npc,
+            creature)
+        npcHandler:setTopic(playerId, 0)
+    end
+    return true
+end
+
+npcHandler:setMessage(MESSAGE_GREET, 'Hi there! I\'m ready to brief you with {tactical} advice.')
```
Comment (rigis1) [inline data/npc/gnomercy.lua]:
```suggestion
npcHandler:setMessage(MESSAGE_GREET, "Hi there! I'm ready to brief you with {tactical} advice.")
```

**Review by rigis1 — APPROVED** [review]

**Comment by murilo09** [comment]
@rigis1 @majestyotbr finished, and I tested the new map and everything is working fine

**Review by guispiller — APPROVED** [review]
Excellent job! Thanks for your contribution

**Review by majestyotbr — APPROVED** [review]

**Comment by majestyotbr** [comment]
Thanks for your contribution. Updated map available in:
https://github.com/opentibiabr/otservbr-global/releases/download/stable-v1.4.0/otservbr.otbm
