### PR TITLE
Fix maxSummons bug

### LINKED ISSUE #380: [Bug]: Number of summons is exceeding the maximum stablished.
### What happened?

General Murius, for exemple, has a maximum number of Minotaur Guards set as 2. Same thing for Minotaur Archers. 

Yet, it happens to be that General Murius is summuning up to 4 Minotaur Guards or 4 Minotaur Archers, clearly a bug somewhere in monster.cpp

### How to Reproduce?

Just summon General Murius.

### Relevant log output

_No response_

### Attach any relevant file

unknown
unknown

### Version

12.x (Default)

### What OS are you seeing the problem on?

Windows 10

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### LINKED ISSUE #389: [Bug]: Familiar time, error + familiar gone upon logout.
### What happened?

Timer issue, img below:
https://gyazo.com/51906eee71f93a192b9b65e58249073e

### How to Reproduce?

Change data\lib\tables\familiar.lua
From
for sendMessage = 1, #timer do
		player:setStorageValue(timer[sendMessage].storage, -1)
	end

to
for sendMessage = 1, #FAMILIAR_TIMER do
        player:setStorageValue(FAMILIAR_TIMER[sendMessage].storage, -1)
    end

### Relevant log output

_No response_

### Attach any relevant file

_No response_

### Version

12.x (Default)

### What OS are you seeing the problem on?

Ubuntu 20.04

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by dudantas**
# Description
Fix for the issue #380 and #389

- Variable ```monster.summons``` renamed to ```monster.summon```
- Improved the ```registerMonsterType.summon``` function. The ```monster.maxSummons``` was changed to be inside ```monster.summon```, thus facilitating development
- Added new table ```summons``` inside of ```monster.summon```
- Added the ```count``` in the ```monsterType:addSummon``` function
- Fixed somes summons with ```Demon2``` name to ```Demon```
- Removed ```monster.summonCost```, the correct is ```monster.manaCost```
- Fixed a bug in the ```registerMonsterType.light``` function
- Fixed bug in the familiar behavior

- [x] Modify all monsters for new style of summons

Thanks @marmichalski, for making the comments in the review.

## Type of change

  - [x] Bug fix (non-breaking change which fixes an issue)

## Checklist

  - [x] My code follows the style guidelines of this project
  - [x] I have performed a self-review of my own code
  - [x] I checked the PR checks reports
  - [x] I have commented my code, particularly in hard-to-understand areas
  - [x] I have made corresponding changes to the documentation
  - [x] My changes generate no new warnings
  - [x] I have added tests that prove my fix is effective or that my feature works

### CODE REVIEW

File: src/creatures/monsters/monster.cpp [hunk 1]
```diff
@@ -1024,7 +1024,7 @@ void Monster::onThinkDefense(uint32_t interval)
 				}
 			}
 
-			if (summonCount >= summonBlock.max) {
+			if (summonCount >= summonBlock.max || summonCount >= mType->info.maxSummons) {
```
Comment (marmichalski) [inline src/creatures/monsters/monster.cpp]: Well, isn't that covered in line 1004?

Comment (dudantas) [reply src/creatures/monsters/monster.cpp]: Apparently no. If it was, it would work and the correction you made would not be necessary.

Comment (marmichalski) [reply src/creatures/monsters/monster.cpp]: That's not entirely true I belive.

summonCount has no way to be higher than info.maxSummons, because, well, it is calculated by iterating over summons - and summons can't be higher than info.maxSummons, because it's checked by line 1004 (also 1011)

Comment (marmichalski) [reply src/creatures/monsters/monster.cpp]: Correction here was to limit summon by it's own maxCount. It was still limited by the info.maxSummons anyway,

Comment (marmichalski) [reply src/creatures/monsters/monster.cpp:1027]: (actually line 1011)

Comment (dudantas) [reply src/creatures/monsters/monster.cpp]: No, maxSummons just doesn't work. Neither here nor on TFS. The reason I don't know, probably has something to do with the switch to revscript.

You see: https://github.com/opentibiabr/otservbr-global/issues/380?

Comment (marmichalski) [reply src/creatures/monsters/monster.cpp]: well, as you can see it's still limtied by the info.maxSummons, which is 4. The problem is it spawns more of them per block than intended 2 - because it was not assigned through lua. Your `||` does nothing. :shrug:

Comment (dudantas) [reply src/creatures/monsters/monster.cpp]: > well, as you can see it's still limtied by the info.maxSummons, which is 4. The problem is it spawns more of them per block than intended 2 - because it was not assigned through lua. Your `||` does nothing. 🤷

Revert your commit, add mine changes and see if my "||" does not do anything.

Comment (marmichalski) [reply src/creatures/monsters/monster.cpp]: Please don't tag me when cherry picking my changes.

**Review by Mirkaanks — COMMENTED** [review]
.

**Comment by Mirkaanks** [comment]
If you change FAMILIAR_TIMER = { **to** FAMILIAR_FAMILIAR_TIMER = {
Will need to change scripts from: 
\data\scripts\creaturescripts\familiar
\data\scripts\spells\summon

**Review by beats-dh — APPROVED** [review]
