### PR TITLE
Fix nightfiend corpse id and loot, carpet npcs keyword

### LINKED ISSUE #707: Flying carpet tavel npc's lack the "fly" command, and the Issavi npc does not work
### Priority

Low

### Area

- [ ] Datapack
- [ ] Source
- [ ] Map
- [X] Other

### What happened?

Most of the carpet traveling npc's don't have "fly" set as a keyword.

The carpet npc in Issavi doesn't work at all, rather - you can fly anywhere with her.

### What OS are you seeing the problem on?

Ubuntu 20.04

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by Bjunken**
# Description
Nightfiend:
The corpse ID was set to the wrong ID and there was no loot table added.
Carpet npc's:
Many of them didn't have "fly" as a keyword and the Issavi carpet npc, didn't work.

### **Actual**

Do this and that doesn't happens

### **Expected**

Do this and that happens

## Fixes
Changed the corpse ID to the correct one and added a loot table, loot is according to the Tibia wiki.
I added in the keyword "fly", so the npc's now tell you where they can fly you.
Re-added the flight options on Tanyt, so you can now travel with her.
\# (issue)

## Type of change

Please delete options that are not relevant.

  - [X ] Bug fix (non-breaking change which fixes an issue)
  - [ ] New feature (non-breaking change which adds functionality)
  - [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
  - [ ] This change requires a documentation update

## How Has This Been Tested

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

  - [X] Test A
  I spawned them in and killed a few of them to make sure they dropped the loot which I had set.
  - [x ] Test B
I tested the npc's in game.
**Test Configuration**:

  - Server Version: Main branch
  - Client: 12.86
  - Operating System: Ubuntu 20.04

## Checklist

  - [X ] My code follows the style guidelines of this project
  - [ X] I have performed a self-review of my own code
  - [X ] I checked the PR checks reports
  - [ X] I have commented my code, particularly in hard-to-understand areas
  - [X ] I have made corresponding changes to the documentation
  - [ X] My changes generate no new warnings
  - [ X] I have added tests that prove my fix is effective or that my feature works

### CODE REVIEW

**Comment by rigis1** [comment]
acording to my source melian should have fly message
image
gwen should have 
image
as i know in loot
chance = 100000 = 100%
chance = 50000 = 50%
and maxcount could be in one line just 148
you can use alias keyword instead same line with just name change

**Comment by Bjunken** [comment]
> acording to my source melian should have fly message image gwen should have image as i know in loot chance = 100000 = 100% chance = 50000 = 50% and maxcount could be in one line just 148 you can use alias keyword instead same line with just name change

Yes, Tanyt, Uzon, Melian and Iyad had the "fly" as a keyword, but the others didn't. Gwen had it, but from what I know, she's suppose to tell you where to fly, so I changed it.

Will take the rest into consideration if I do any other pull requests :)

File: data/npc/tanyt.lua [hunk 1]
```diff
@@ -70,15 +70,15 @@ end
...
-addTravelKeyword('hills', 60, Position(32536, 31837, 4))
-addTravelKeyword('edron', 60, Position(33193, 31784, 3))
+addTravelKeyword('darashia', 'Darashia on Darama', 40, Position(33270, 32441, 6))
+addTravelKeyword('darama', 'Darashia on Darama', 40, Position(33270, 32441, 6))
+addTravelKeyword('kazordoon', 'Kazordoon', 70, Position(32588, 31941, 0))
+addTravelKeyword('kazor', 'Kazordoon', 70, Position(32588, 31941, 0))
+addTravelKeyword('femor hills', 'the Femor Hills', 60, Position(32536, 31837, 4))
+addTravelKeyword('hills', 'the Femor Hills', 60, Position(32536, 31837, 4))
+addTravelKeyword('svargrond', 'Svargrond', 60, Position(32253, 31097, 4))
+addTravelKeyword('issavi', 'Issavi', 100, Position(33957, 31515, 0))
```
Comment (Bjunken) [inline data/npc/tanyt.lua:80]: Ops

**Review by majestyotbr — APPROVED** [review]

**Review by majestyotbr — APPROVED** [review]
