### PR TITLE
[Fix] talkDelay from npcs

### LINKED ISSUE #486: [Bug]: NPC's Warzones 4-5-6
### What happened?

When saying Hi to these 3 NPCs, none of them respond and the following errors appear on the console

- Klom Stonecutter
- Gnomus
- Lardoc Bashsmite

i used Debian 11

### How to Reproduce?

- Klom Stonecutter
`[2022-08-03 00:40:06.667] [error] Lua script error:
scriptInterface: [Scripts Interface]
scriptId: [/home/canary/data/npclua/klom_stonecutter.lua:callback]
timerEvent: []
 callbackId:[]
function: []
error [data/npclib/npc_system/npc_handler.lua:584: attempt to perform arithmetic on a boolean value
stack traceback:
        [C]: in function '__mul'
        data/npclib/npc_system/npc_handler.lua:584: in function 'say'
        data/npclib/npc_system/npc_handler.lua:374: in function 'greet'
        data/npclib/npc_system/npc_handler.lua:495: in function 'onGreet'
        data/npclib/npc_system/modules.lua:343: in function 'callback'
        data/npclib/npc_system/keyword_handler.lua:31: in function 'processMessage'
        data/npclib/npc_system/keyword_handler.lua:188: in function 'processNodeMessage'
        data/npclib/npc_system/keyword_handler.lua:153: in function 'processMessage'
        data/npclib/npc_system/npc_handler.lua:414: in function 'onSay'
        /home/canary/data/npclua/klom_stonecutter.lua:46: in function </home/canary/data/npclua/klom_stonecutter.lua:45>]
`

- Gnomus
`[2022-08-03 00:41:25.436] [error] Lua script error:
scriptInterface: [Scripts Interface]
scriptId: [/home/canary/data/npclua/gnomus.lua:callback]
timerEvent: []
 callbackId:[]
function: []
error [data/npclib/npc_system/npc_handler.lua:584: attempt to perform arithmetic on a boolean value
stack traceback:
        [C]: in function '__mul'
        data/npclib/npc_system/npc_handler.lua:584: in function 'say'
        data/npclib/npc_system/npc_handler.lua:374: in function 'greet'
        data/npclib/npc_system/npc_handler.lua:495: in function 'onGreet'
        data/npclib/npc_system/modules.lua:343: in function 'callback'
        data/npclib/npc_system/keyword_handler.lua:31: in function 'processMessage'
        data/npclib/npc_system/keyword_handler.lua:188: in function 'processNodeMessage'
        data/npclib/npc_system/keyword_handler.lua:153: in function 'processMessage'
        data/npclib/npc_system/npc_handler.lua:414: in function 'onSay'
        /home/canary/data/npclua/gnomus.lua:46: in function </home/canary/data/npclua/gnomus.lua:45>]
`

- Lardoc Bashsmite
`[2022-08-03 00:41:55.055] [error] Lua script error:
scriptInterface: [Scripts Interface]
scriptId: [/home/canary/data/npclua/lardoc_bashsmite.lua:callback]
timerEvent: []
 callbackId:[]
function: []
error [data/npclib/npc_system/npc_handler.lua:584: attempt to perform arithmetic on a boolean value
stack traceback:
        [C]: in function '__mul'
        data/npclib/npc_system/npc_handler.lua:584: in function 'say'
        data/npclib/npc_system/npc_handler.lua:374: in function 'greet'
        data/npclib/npc_system/npc_handler.lua:495: in function 'onGreet'
        data/npclib/npc_system/modules.lua:343: in function 'callback'
        data/npclib/npc_system/keyword_handler.lua:31: in function 'processMessage'
        data/npclib/npc_system/keyword_handler.lua:188: in function 'processNodeMessage'
        data/npclib/npc_system/keyword_handler.lua:153: in function 'processMessage'
        data/npclib/npc_system/npc_handler.lua:414: in function 'onSay'
        /home/canary/data/npclua/lardoc_bashsmite.lua:46: in function </home/canary/data/npclua/lardoc_bashsmite.lua:45>]
`

### Relevant log output

_No response_

### Attach any relevant file

wz456

### Version

12.x (Default)

### What OS are you seeing the problem on?

Debian 11

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by dudantas**
Resolves #486

Added delay to the function "NpcHandler:setMessage" and fixed talkDelay from the others functions. 
The modifications only apply to speeches that contain more than one message.

For example: 
```lua
npcHandler:say({"message1", "message2"})
```
```lua
npcHandler:setMessage(MESSAGE_GREET, {"message1", "message2"})
```

Example of manual delayed message:
For example: 
```lua
npcHandler:say({"message1", "message2", npc, player, 5000})
```
```lua
npcHandler:setMessage(MESSAGE_GREET, {"message1", "message2"}, 5000)
```

5000 = 5 seconds of interval from each message
If the delay is not added to one of the functions, the default delay of 1 second interval between each message will be added

### CODE REVIEW

File: data/npclua/klom_stonecutter.lua [hunk 1]
```diff
@@ -53,16 +53,21 @@ end
 npcConfig.voices = {
 	interval = 15000,
 	chance = 50,
-	{text = 'abc'} }
-local quantidade = {}
+	{text = 'abc'}
```
Comment (dybik08) [inline data/npclua/klom_stonecutter.lua]:
```suggestion
	{text = 'Ah.'},
	{text = 'We need more volunteers!'},
	{text = 'And they call this "deep"...'},
	{text = 'Preparation is paramount.'},
```

Source: https://tibia.fandom.com/wiki/Klom_Stonecutter

**Review by dybik08 — APPROVED** [review]
tested locally - everything works fine, good job!

**Comment by mattyx14** [comment]
I think there is also a detail when buying when you no longer have capacity and you activate the option to ignore capacity, it does not continue to sell you

**Comment by dudantas** [comment]
> I think there is also a detail when buying when you no longer have capacity and you activate the option to ignore capacity, it does not continue to sell you

Thanks for reporting, if you can create an issue. I check until the end of the week and send the fix.

**Review by majestyotbr — APPROVED** [review]

**Review by omeranha — APPROVED** [review]
