### PR TITLE
Fix missing monsters loot, skinning corpses and npcs keywords

### LINKED ISSUE #612: *zethra.lua trade option missing
### Priority

Enhancement

### Area

- [X] Datapack
- [ ] Source
- [ ] Map
- [ ] Other

### What is missing?

[Zethra](https://tibia.fandom.com/wiki/Zethra#:~:text=Buys,1) should be able to trade with the player.
```
npcConfig.shop = 
{
	{ itemName = "backpack", clientId = 2854, buy = 10 },
	{ itemName = "bag", clientId = 2853, buy = 4 },
	{ itemName = "fishing rod", clientId = 3483, buy = 150, sell = 30 },
	{ itemName = "rope", clientId = 3003, buy = 50, sell = 8 },
	{ itemName = "scroll", clientId = 2815, buy = 5 },
	{ itemName = "scythe", clientId = 3453, buy = 12 },
	{ itemName = "shovel", clientId = 3457, buy = 10, sell = 2 },
	{ itemName = "torch", clientId = 2920, buy = 2 },
	{ itemName = "worm", clientId = 3492, buy = 1 }
}

-- On buy npc shop message
npcType.onBuyItem = function(npc, player, itemId, subType, amount, inBackpacks, name, totalCost)
	npc:sellItem(player, itemId, amount, subType, true, inBackpacks, 2854)
	player:sendTextMessage(MESSAGE_INFO_DESCR, string.format("Bought %ix %s for %i %s.", amount, name, totalCost, ItemType(npc:getCurrency()):getPluralName():lower()))
end

-- On sell npc shop message
npcType.onSellItem = function(npc, player, clientId, subtype, amount, name, totalCost)
	player:sendTextMessage(MESSAGE_INFO_DESCR, string.format("Sold %ix %s for %i gold.", amount, name, totalCost))
end

-- On check npc shop message (look item)
npcType.onCheckItem = function(npc, player, clientId, subType)
end
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by rigis1**
# Description

+Zethra now is able to trade
+Gloom wolf now drops Gloom Wolf Fur
+Ghost wolf now drops gold coins
+Lizard legionnaire is now skinnable 
+Traveling cost is more accurate
+Additional chatlines 
+Twisted pooka drops more accurate loot
+Pixie drops more accurate loot
+Nymph drops more accurate loot
+Boogy drops more accurate loot
+Dragon and Grand Mother Foulscale now have corpse protection, skinning and autoloot.

### **Actual**

Zethra not offer trade opportunity
You can't skin Lizard legionnaire corpse
Pino offer to travel to edron.

### **Expected**

Zethra now is able to trade, monsters drops more accurate loot and flying cost is as it should be.
Lizard legionnaire is now skinnable.
Pino flies only to Darashia, Svargrond, Femor Hills, Kazordoon, Zao and Issavi.

## Fixes
Resolves #612

## Type of change

Please delete options that are not relevant.

  - [x] Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested
Go to Adventurers' Guild and start trade with Zethra
Kill Lizard legionnaire and use obsidian knife on its corpse.
Go to Pino and type Edron.
## Checklist

  - [x] My code follows the style guidelines of this project
  - [x] I have performed a self-review of my own code
  - [x] I checked the PR checks reports
  - [x] I have commented my code, particularly in hard-to-understand areas
  - [ ] I have made corresponding changes to the documentation
  - [x] My changes generate no new warnings
  - [ ] I have added tests that prove my fix is effective or that my feature works

### CODE REVIEW

File: data/monster/fey/boogy.lua [hunk 1]
```diff
@@ -95,6 +95,9 @@ monster.loot = {
 	{id = 677, chance = 3000, maxCount = 3}, -- small enchanted emerald
 	{id = 236, chance = 15000}, -- strong health potion
 	{id = 814, chance = 3200}, -- terra amulet
+	{name = "Fairy Wings", chance = 15000},
+	{name = "Wooden Spellbook", chance = 3440},
+	{name = "Leaf Star", chance = 3440, maxCount = 7},
```
Comment (guispiller) [inline data/monster/fey/boogy.lua]: Could you please just fix these 3 lines to keep the standard of all other monsters? If the loot is registered by the name, please use all letters with lower case. Thanks for your contribution

File: data/monster/fey/twisted_pooka.lua [hunk 2]
```diff
@@ -94,6 +94,8 @@ monster.loot = {
 	{name = "fairy wings", chance = 30100},
 	{name = "orange mushroom", chance = 5155},
 	{name = "shimmering beetles", chance = 591},
+	{name = "Prismatic Quartz", chance = 2500},
+	{name = "Crystal of Focus", chance = 60},
```
Comment (guispiller) [inline data/monster/fey/twisted_pooka.lua]: Could you please just fix these 2 lines to keep the standard of all other monsters? If the loot is registered by the name, please use all letters with lower case. Thanks for your contribution.

**Review by majestyotbr — APPROVED** [review]

**Review by majestyotbr — APPROVED** [review]

**Review by guispiller — APPROVED** [review]
Nice job. Thanks for your contribution!
